### ISSUE TITLE
sdgym.benchmark function bug

### ISSUE THREAD

**Issue by johnson18404** [DAI-Lab/SDGym#10]
Hello DAI-Lab, recently I am researching on data synthesizing and I found this amazing project.
I got an error when running `sdgym.benchmark()` function. 

![image](https://user-images.githubusercontent.com/13941886/62620930-24a62780-b94d-11e9-82f7-1f6cd06c1afb.png)

After tracking some codes. I think the variable `synthesized` should be a synthesized data produced by `synthesizer.sample()`.
So we can solve this problem by replacing line 37:

```
synthesized = synthesizer(train, categoricals, ordinals)
```

into

```
synthesizer.fit(train, categoricals, ordinals)
synthesized = synthesizer.sample(train.shape[0])
```

**Comment by csala** [comment]
Hi @johnson18404 Thanks for reporting this.

The problem that you see is that the `synthesizer` argument of the `benchmark` function is expected to be a `callable`, which means that it can either be a `function` or `method`, but not a class instance.

If you look at the [Benchmarking the Demo Synthesizers](https://github.com/DAI-Lab/SDGym#benchmarking-the-demo-synthesizers) section in the README, you will find an example about how to evaluate the included synthesizers using the `benchmark` function, which is by passing the `synthesizer.fit_sample` method to the `benchmark` function:

```
synthesizer = IndependentSynthesizer()
scores = benchmark(synthesizer.fit_sample)
```

**Comment by johnson18404** [comment]
I get it. It seems that I misunderstood the argument meanings. Thank you.
