### ISSUE TITLE
Removal of RNN and attention in TGAN

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [DAI-Lab/SDGym#5]
Hi guys, sorry for bothering you again! 

I noticed the TGAN model was changed, removing the recurrent structure as well as the attention layer. I was wondering why these were made, since the original performed very well. Was it due to space/time limitations in this new setup? Or did you also see improved results with these changes?

**Comment by leix28** [comment]
Yeah, mostly due to time complexity. We found that a simple MLP can perform as good as LSTM.
